import type { Metadata } from "next";
import "../globals.css";

import { cn } from "@/lib/utils";
import TopSideBar from "@/components/layouts/TopSideBar";
import LeftSideBar from "@/components/layouts/LeftSideBar";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider } from "@/lib/ToastProvider";


export const metadata: Metadata = {
  title: "Dk Store admin",
  description: "Generated by create Dk",
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased w-full",
          )}
        >
          <ToastProvider />
          <TopSideBar />
          <div className="flex">
            <LeftSideBar />
            <div className="w-full container mx-auto my-10">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
